version: "3.9"
services:
    postgres:
        container_name: psqlZhF
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: "ZhFDb"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "1234"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    postgres-data: